name: cd app
on:
  push:
    branches:
      - master
      - 'chore/add-app-package'
    paths:
      - 'app'
      - 'packages/core'
      - 'Dockerfile'
jobs:
  build-and-deploy:
    name: Deploy app to Heroku
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      HEROKU_API_KEY: ${{ secrets.LANDING__HEROKU_OAUTH_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make env file
      run: |
        cat > app/.env << EOF
        API_URL=https://auth-api-test.herokuapp.com
        EOF

    - name: Build docker
      run: docker build -t registry.heroku.com/montelearn-app/web .

    - name: Login to Heroku Container registry
      run: heroku container:login

    - name: Push container
      run: docker push registry.heroku.com/montelearn-app/web

    - name: Release container
      run: heroku container:release web --app montelearn-app
