name: CD Landing Page (test)
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cd-landing.yml'
      - '.dockerignore'
      - 'landing'
      - 'packages/core'
      - 'Dockerfile'
jobs:
  build-and-deploy:
    name: Deploy landing to Heroku
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      HEROKU_API_KEY: ${{ secrets.LANDING__HEROKU_OAUTH_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make env file
      run: |
        cat > landing/.env << EOF
        API_PLAYGROUND_URL=https://auth-api-test.herokuapp.com
        EOF

    - name: Build docker
      run: |
        docker build -t registry.heroku.com/montelearn-landing/web \
        --target landing-runner .

    - name: Login to Heroku Container registry
      run: heroku container:login

    - name: Push container
      run: docker push registry.heroku.com/montelearn-landing/web

    - name: Release container
      run: heroku container:release web --app montelearn-landing
