name: CI Frontend
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  lint-and-build:
    name: Lint and build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.11.0'

    - name: Get yarn cache dir
      id: yarn-cache-output
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Restore yarn global cache
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-output.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Restore node_modules cache
      uses: actions/cache@v1
      id: node-modules-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install NPM packages
      run: yarn --frozen-lockfile

    - name: Build packages
      run: npx lerna run lib

    - name: Type checking
      run: npx lerna run tsc

    - name: ESLint
      run: npx lerna run lint

    - name: Run unit tests
      run: npx lerna run test

    - name: Build landing page
      env:
        API_PLAYGROUND_URL: http://localhost:8000
      run: (cd landing && yarn build)
